//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pharmacy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbPharmacyEntities : DbContext
    {
        private static dbPharmacyEntities _context;

        public dbPharmacyEntities()
            : base("name=dbPharmacyEntities") {
        }

        public static dbPharmacyEntities getContext() {
            if (_context == null) {
                _context = new dbPharmacyEntities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dbAuth> dbAuth { get; set; }
        public virtual DbSet<dbStock1> dbStock1 { get; set; }
        public virtual DbSet<dbStock2> dbStock2 { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
